import type { Project } from "./types";
import { assetUrl } from "./utils";

export const projects: Project[] = [
  {
    slug: "levc-insignia",
    thumbnail: { src: assetUrl("/images/work/02.jpg"), alt: "LEVC Heritage Emblem" },
    hasVideo: true,
    cover: { src: assetUrl("/images/projects/levc-insignia/01.jpg"), alt: "LEVC new emblem — close-up on bonnet with rain droplets" },
    blocks: [
      { _type: "text", _key: "levc-t1", content: "A new identity begins in 2D" },
      { _type: "before-after", _key: "levc-ba1", before: { src: assetUrl("/images/projects/levc-insignia/slider1-before.jpg"), alt: "Legacy graphic identity — old LEVC logo and TX taxi", width: 1755, height: 897 }, after: { src: assetUrl("/images/projects/levc-insignia/slider1-after.jpg"), alt: "Approved 2D redesign — new LEVC logo and L380", width: 1755, height: 897 } },
      { _type: "text", _key: "levc-d1", content: "The new graphic direction had already been defined in 2D. My role began by translating that approved identity into a resolved 3D emblem." },
      { _type: "text", _key: "levc-t2", content: "3D form exploration" },
      { _type: "image-full", _key: "levc-02", image: { src: assetUrl("/images/projects/levc-insignia/02.jpg"), alt: "LEVC insignia — design sketches and 3D explorations" } },
      { _type: "text", _key: "levc-d2", content: "Starting from the approved 2D artwork, the work focused on exploring how the emblem should exist in three dimensions through relief, proportion, texture, edge definition and overall visual character." },
      { _type: "text", _key: "levc-t3", content: "From identity to emblem" },
      { _type: "before-after", _key: "levc-ba2", before: { src: assetUrl("/images/projects/levc-insignia/slider2-before.jpg"), alt: "Approved graphic identity — 2D emblem on wood surface", width: 1754, height: 897 }, after: { src: assetUrl("/images/projects/levc-insignia/slider2-after.jpg"), alt: "Production-ready emblem — 3D emblem on wood surface", width: 1754, height: 897 } },
      { _type: "text", _key: "levc-d3", content: "The challenge was to turn a flat approved identity into a physical emblem with depth, precision, perceived quality and production logic." },
      { _type: "text", _key: "levc-t4", content: "From legacy badge to refined emblem" },
      { _type: "before-after", _key: "levc-ba3", before: { src: assetUrl("/images/projects/levc-insignia/slider3-after.jpg"), alt: "Earlier badge — previous generation emblem", width: 1754, height: 897 }, after: { src: assetUrl("/images/projects/levc-insignia/slider3-before.jpg"), alt: "Refined emblem — new production-ready 3D emblem", width: 1754, height: 897 } },
      { _type: "text", _key: "levc-d4", content: "The evolution went beyond updating the form. It required refining proportions, relief, texture, radii and overall surface clarity to achieve a lighter, sharper and more premium result." },
      { _type: "text", _key: "levc-t5", content: "Built for the bonnet" },
      { _type: "image-full", _key: "levc-03", image: { src: assetUrl("/images/projects/levc-insignia/03.jpg"), alt: "LEVC emblem — 3D wireframe model on bonnet curvature" } },
      { _type: "text", _key: "levc-d5", content: "The emblem was modelled directly on the real bonnet curvature, ensuring accurate fit, controlled geometry and a production-ready relationship with the vehicle surface." },
      { _type: "video", _key: "levc-video", video: { src: assetUrl("/videos/levc-insignia.mp4") } },
      { _type: "text", _key: "levc-t6", content: "Applied in production" },
      { _type: "image-full", _key: "levc-04", image: { src: assetUrl("/images/projects/levc-insignia/04.jpg"), alt: "LEVC emblem — close-up on blue bonnet and L380 full vehicle" } },
      { _type: "image-full", _key: "levc-05", image: { src: assetUrl("/images/projects/levc-insignia/05.jpg"), alt: "LEVC emblem — close-up on white bonnet and full vehicle front view" } },
    ],
  },
  {
    slug: "levc-l380",
    thumbnail: { src: assetUrl("/images/work/12.jpg"), alt: "LEVC L380 Bespoke Rear Cabin Development" },
    hasVideo: false,
    cover: { src: assetUrl("/images/projects/levc-l380/01.jpg"), alt: "LEVC L380 — red bespoke variant with rear cabin open" },
    blocks: [
      { _type: "image-full", _key: "l380-02", image: { src: assetUrl("/images/projects/levc-l380/02.jpg"), alt: "LEVC L380 — both bespoke variants on display" } },
      { _type: "text", _key: "l380-t1", content: "Two bespoke interpretations" },
      { _type: "image-full", _key: "l380-03", image: { src: assetUrl("/images/projects/levc-l380/03.jpg"), alt: "LEVC L380 — red and blue variant rear cabin interiors" } },
      { _type: "text", _key: "l380-d1", content: "Two bespoke L380 variants were developed to explore different rear-cabin experiences. One focused on a more executive lounge layout with a rotating central seat and work-oriented table solution, while the other introduced functions more related to storage, luggage and hospitality." },
      { _type: "text", _key: "l380-t2", content: "Divider and main architecture" },
      { _type: "image-full", _key: "l380-04", image: { src: assetUrl("/images/projects/levc-l380/04.jpg"), alt: "LEVC L380 — rear divider with display, modules and service compartments" } },
      { _type: "text", _key: "l380-d2", content: "The core of the work focused on the full development of the rear divider, including its connection to the side pillars, roof and floor, as well as the integration of all major functions within one single architectural element. The divider had to resolve privacy, communication, media, storage, ventilation, hospitality and access within a highly restricted space and with a clearly production-oriented approach." },
      { _type: "text", _key: "l380-t3", content: "Integrated functions" },
      { _type: "image-full", _key: "l380-05", image: { src: assetUrl("/images/projects/levc-l380/05.jpg"), alt: "LEVC L380 — rear divider with annotated function callouts" } },
      { _type: "text", _key: "l380-d3", content: "From top to bottom, the divider integrated variable privacy glass, display, electronically controlled vents, audio system, upper drawers for personal objects, sliding side modules, central bottle and glass refrigeration, side access handles, umbrella system with drainage, and a lower aluminium part connecting the divider to the floor while integrating HVAC and lighting." },
      { _type: "image-full", _key: "l380-06", image: { src: assetUrl("/images/projects/levc-l380/06.jpg"), alt: "LEVC L380 — detail callouts for fold-out table, umbrella, treadplate, handles, speakers and HVAC" } },
      { _type: "text", _key: "l380-t4", content: "Sliding modules and hospitality functions" },
      { _type: "image-full", _key: "l380-07", image: { src: assetUrl("/images/projects/levc-l380/07.jpg"), alt: "LEVC L380 — sliding service modules with tea, storage and refrigeration" } },
      { _type: "text", _key: "l380-d4", content: "The lower modules were developed as functional islands sliding on floor rails, allowing different usage layouts. Depending on the variant, they integrated work-related functions, personal storage, tea service, shoe storage and refrigerated bottle and glass presentation." },
      { _type: "text", _key: "l380-t5", content: "Details shaped by real use" },
      { _type: "image-full", _key: "l380-08", image: { src: assetUrl("/images/projects/levc-l380/08.jpg"), alt: "LEVC L380 — illuminated treadplate, umbrella and side entry details" } },
      { _type: "text", _key: "l380-d5", content: "Beyond the main architecture, several smaller but technically sensitive components were developed as part of the complete rear cabin experience, including illuminated treadplates, side access handles, the umbrella with leather upper retention and lower drainage, and the integration of ambient lighting and HVAC within the lower aluminium structure." },
      { _type: "text", _key: "l380-t6", content: "Bespoke storage and travel solution" },
      { _type: "image-full", _key: "l380-09", image: { src: assetUrl("/images/projects/levc-l380/09.jpg"), alt: "LEVC L380 — red variant rear access with luggage storage" } },
      { _type: "text", _key: "l380-d6", content: "One of the variants explored a more travel-oriented concept, integrating storage, luggage and hospitality functions within a highly personalised rear cabin." },
      { _type: "text", _key: "l380-t7", content: "Executive lounge configuration" },
      { _type: "image-full", _key: "l380-10", image: { src: assetUrl("/images/projects/levc-l380/10.jpg"), alt: "LEVC L380 — blue variant rear with luggage compartment" } },
      { _type: "text", _key: "l380-d7", content: "The second variant focused on a more executive configuration, combining a refined atmosphere with work-oriented functions and a more private lounge-like experience." },
      { _type: "text", _key: "l380-t8", content: "Built and exhibited" },
      { _type: "image-full", _key: "l380-11", image: { src: assetUrl("/images/projects/levc-l380/11.jpg"), alt: "LEVC L380 — both bespoke variants, full vehicle exterior" } },
      { _type: "text", _key: "l380-d8", content: "Both bespoke L380 vehicles were fully developed and presented as real, production-oriented show vehicles, turning the project into a built and tangible proof of concept rather than a purely digital proposal." },
    ],
  },
  {
    slug: "luxury-ev-knob",
    thumbnail: { src: assetUrl("/images/work/03.jpg"), alt: "Luxury EV Central Control Knob Concept" },
    hasVideo: true,
    blocks: [
      { _type: "text", _key: "knob-t1", content: "From silent luxury to intelligent control" },
      { _type: "before-after", _key: "knob-ba1", before: { src: assetUrl("/images/projects/luxury-ev-knob/slider-before.jpg"), alt: "Technology, when needed — knob with active interface", width: 1754, height: 911 }, after: { src: assetUrl("/images/projects/luxury-ev-knob/slider-after.jpg"), alt: "Luxury, when silent — knob in dormant state", width: 1754, height: 912 } },
      { _type: "text", _key: "knob-d1", content: "When inactive, the component reads as a refined luxury detail. When activated, it reveals a layered interaction system designed to expand functionality without increasing visual noise inside the cabin." },
      { _type: "text", _key: "knob-t2", content: "One control, multiple functions" },
      { _type: "video", _key: "knob-video-1", video: { src: assetUrl("/videos/luxury-ev-knob-1.mp4") } },
      { _type: "text", _key: "knob-d2", content: "The knob was designed to manage multiple vehicle functions through one compact interaction point, reducing interface clutter while preserving intuitive use and visual clarity." },
      { _type: "text", _key: "knob-t3", content: "A dynamic interface system" },
      { _type: "video", _key: "knob-video-2", video: { src: assetUrl("/videos/luxury-ev-knob-2.mp4") } },
      { _type: "text", _key: "knob-d3", content: "The central touchscreen and the dedicated display behind the black crystal work together as one system, adapting graphics, colour and feedback to each active function." },
      { _type: "text", _key: "knob-t4", content: "Inside the Knob" },
      { _type: "before-after", _key: "knob-ba2", before: { src: assetUrl("/images/projects/luxury-ev-knob/slider2-before.jpg"), alt: "Internal Architecture — layered interaction system exploded view", width: 1755, height: 913 }, after: { src: assetUrl("/images/projects/luxury-ev-knob/slider2-after.jpg"), alt: "Exterior Presence — assembled knob on display surface", width: 1755, height: 912 } },
      { _type: "text", _key: "knob-d4", content: "Behind its calm exterior, the knob is built as a layered interaction system. A dedicated background display, central touch surface, haptic click feedback, electronic core, LED illumination and textured crystal ring work together to combine functional complexity with luxury presence." },
      { _type: "text", _key: "knob-t5", content: "Layered Interaction Architecture" },
      { _type: "image-full", _key: "knob-01", image: { src: assetUrl("/images/projects/luxury-ev-knob/01.jpg"), alt: "Luxury EV control knob — layered architecture diagram with component callouts" } },
      { _type: "text", _key: "knob-d5", content: "The project was developed as a compact architecture of visual, tactile and material feedback. Each layer contributes to a different aspect of the interaction, from touch and click response to illumination, surface expression and display integration." },
      { _type: "text", _key: "knob-t6", content: "Precision in a compact object" },
      { _type: "image-full", _key: "knob-02", image: { src: assetUrl("/images/projects/luxury-ev-knob/02.jpg"), alt: "Luxury EV control knob — in context, active interface with illuminated crystal ring" } },
      { _type: "text", _key: "knob-d6", content: "The component was designed to feel highly resolved in every state: as a sculptural luxury detail when off, and as an advanced multifunctional interface when active." },
    ],
  },
  {
    slug: "speaker-concept",
    thumbnail: { src: assetUrl("/images/work/04.jpg"), alt: "Trumpet-Inspired Speaker Concept" },
    hasVideo: true,
    blocks: [
      { _type: "before-after", _key: "spk-ba", before: { src: assetUrl("/images/projects/speaker-concept/slider-before.jpg"), alt: "Inspired by the trumpet — sketch of musician playing", width: 1781, height: 926 }, after: { src: assetUrl("/images/projects/speaker-concept/slider-after.jpg"), alt: "Shaped into sound — sketch of speaker integrated in door panel", width: 1781, height: 926 } },
      { _type: "image-full", _key: "spk-01", image: { src: assetUrl("/images/projects/speaker-concept/01.jpg"), alt: "Concept sketch — trumpet player emerging from door panel architecture" } },
      { _type: "video", _key: "spk-video", video: { src: assetUrl("/videos/speaker-concept.mp4") } },
      { _type: "text", _key: "spk-text-1", content: "The project addressed a common challenge in luxury interiors: how to integrate a high-end audio component without making it feel purely technical or visually added-on. The response was to develop the speaker as a sculptural object, using the trumpet as a reference for precision, crafted metal surfaces and sound projection, while reinforcing the interior's material and emotional character." },
      { _type: "image-full", _key: "spk-02", image: { src: assetUrl("/images/projects/speaker-concept/02.jpg"), alt: "Speaker integrated in door panel — light interior, wood and leather" } },
      { _type: "image-full", _key: "spk-03", image: { src: assetUrl("/images/projects/speaker-concept/03.jpg"), alt: "Speaker close-up — Bang & Olufsen branding with crystal detail" } },
      { _type: "image-pair", _key: "spk-pair", left: { src: assetUrl("/images/projects/speaker-concept/04.jpg"), alt: "Speaker on saxophone and sheet music — musical heritage reference" }, right: { src: assetUrl("/images/projects/speaker-concept/05.jpg"), alt: "Speaker detail — Bang & Olufsen text and crystal pattern" } },
      { _type: "text", _key: "spk-text-2", content: "A secondary proposal explored a circular centre composition while preserving the same acoustic identity, material language and luxury positioning." },
      { _type: "image-full", _key: "spk-06", image: { src: assetUrl("/images/projects/speaker-concept/06.jpg"), alt: "Circular design variant — B&O logo, dark background" } },
      { _type: "image-full", _key: "spk-07", image: { src: assetUrl("/images/projects/speaker-concept/07.jpg"), alt: "Full-scale interior review — designer evaluating component in clay model" } },
    ],
  },
  {
    slug: "luxury-ev-steering-wheel",
    thumbnail: { src: assetUrl("/images/work/01.jpg"), alt: "Luxury EV Steering Wheel Concept" },
    hasVideo: true,
    blocks: [
      { _type: "image-full", _key: "lev-a01", image: { src: assetUrl("/images/projects/luxury-ev-steering-wheel/a01.jpg"), alt: "Luxury EV steering wheel — hero image" } },
      { _type: "video", _key: "lev-video", video: { src: assetUrl("/videos/luxury-ev-steering-wheel.mp4") } },
      { _type: "image-full", _key: "lev-01", image: { src: assetUrl("/images/projects/luxury-ev-steering-wheel/01.jpg"), alt: "Luxury EV steering wheel — interior view, warm lighting" } },
      { _type: "image-full", _key: "lev-02", image: { src: assetUrl("/images/projects/luxury-ev-steering-wheel/02.jpg"), alt: "Luxury EV steering wheel — interior view, dark ambience" } },
      { _type: "image-pair", _key: "lev-pair", left: { src: assetUrl("/images/projects/luxury-ev-steering-wheel/03.jpg"), alt: "Luxury EV steering wheel — front view, black background" }, right: { src: assetUrl("/images/projects/luxury-ev-steering-wheel/04.jpg"), alt: "Luxury EV steering wheel — close-up detail, controls and crystal" } },
      { _type: "image-loop", _key: "lev-loop", images: [
        { src: assetUrl("/images/projects/luxury-ev-steering-wheel/loop-01.jpg"), alt: "Steering wheel detail — wood and crystal inlay, ambient off", width: 1754, height: 639 },
        { src: assetUrl("/images/projects/luxury-ev-steering-wheel/loop-02.jpg"), alt: "Steering wheel detail — wood and crystal inlay, ambient on", width: 1754, height: 639 },
      ], interval: 1500 },
      { _type: "image-full", _key: "lev-05", image: { src: assetUrl("/images/projects/luxury-ev-steering-wheel/05.jpg"), alt: "Design process — VR validation with 3D-printed prototype" } },
    ],
  },
  {
    slug: "luxury-ev-console",
    thumbnail: { src: assetUrl("/images/work/11.jpg"), alt: "Luxury EV Center Console Concept" },
    hasVideo: false,
    blocks: [
      { _type: "before-after", _key: "con-ba", before: { src: assetUrl("/images/projects/luxury-ev-console/slider-before.jpg"), alt: "Charging Surface — wireless charging with automatic tilt", width: 2401, height: 1249 }, after: { src: assetUrl("/images/projects/luxury-ev-console/slider-after.jpg"), alt: "Interactive Control Surface — digital control interface", width: 2401, height: 1249 } },
      { _type: "image-full", _key: "con-01", image: { src: assetUrl("/images/projects/luxury-ev-console/01.jpg"), alt: "Center console — close-up, charging surface with crystal detail and ambient lighting" } },
      { _type: "image-full", _key: "con-02", image: { src: assetUrl("/images/projects/luxury-ev-console/02.jpg"), alt: "Center console — side view, leather and stitching detail" } },
      { _type: "image-full", _key: "con-03", image: { src: assetUrl("/images/projects/luxury-ev-console/03.jpg"), alt: "Center console — in context, natural light interior" } },
      { _type: "image-full", _key: "con-04", image: { src: assetUrl("/images/projects/luxury-ev-console/04.jpg"), alt: "Luxury EV — full vehicle exterior, coastal road" } },
      { _type: "image-full", _key: "con-05", image: { src: assetUrl("/images/projects/luxury-ev-console/05.jpg"), alt: "Full-scale prototyping — designer working on clay model interior" } },
    ],
  },
  {
    slug: "chopard-clock",
    thumbnail: { src: assetUrl("/images/work/07.jpg"), alt: "Chopard Clock Concept for Luxury EV Interior" },
    hasVideo: true,
    blocks: [
      { _type: "video", _key: "chop-video-1", video: { src: assetUrl("/videos/chopard-clock-1.mp4") } },
      { _type: "image-full", _key: "chop-01", image: { src: assetUrl("/images/projects/chopard-clock/01.jpg"), alt: "Chopard clock — turbine inspiration blueprint, aircraft engine diagrams" } },
      { _type: "before-after", _key: "chop-ba", before: { src: assetUrl("/images/projects/chopard-clock/slider-before.jpg"), alt: "Chopard clock — aircraft turbine wireframe inspiration", width: 1754, height: 986 }, after: { src: assetUrl("/images/projects/chopard-clock/slider-after.jpg"), alt: "Chopard clock — final clock concept wireframe", width: 1754, height: 986 } },
      { _type: "video", _key: "chop-video-2", video: { src: assetUrl("/videos/chopard-clock-2.mp4") } },
      { _type: "image-full", _key: "chop-02", image: { src: assetUrl("/images/projects/chopard-clock/02.jpg"), alt: "Chopard clock — dashboard mount, light interior, blue dial" } },
      { _type: "image-full", _key: "chop-03", image: { src: assetUrl("/images/projects/chopard-clock/03.jpg"), alt: "Chopard clock — console mount, dark interior, blue dial" } },
      { _type: "image-full", _key: "chop-04", image: { src: assetUrl("/images/projects/chopard-clock/04.jpg"), alt: "Chopard clock — rear console, white dial, wood trim" } },
      { _type: "image-full", _key: "chop-05", image: { src: assetUrl("/images/projects/chopard-clock/05.jpg"), alt: "Chopard clock — rear console, white dial, close-up" } },
    ],
  },
  {
    slug: "pagani-steering-wheel",
    thumbnail: { src: assetUrl("/images/work/05.jpg"), alt: "Pagani Steering Wheel Concept" },
    hasVideo: true,
    blocks: [
      { _type: "image-full", _key: "pag-01", image: { src: assetUrl("/images/projects/pagani-steering-wheel/01.jpg"), alt: "Pagani Huayra steering wheel — design sketch, front view" } },
      { _type: "image-full", _key: "pag-02", image: { src: assetUrl("/images/projects/pagani-steering-wheel/02.jpg"), alt: "Pagani Huayra steering wheel — tan leather on designer desk with sketches" } },
      { _type: "image-full", _key: "pag-03", image: { src: assetUrl("/images/projects/pagani-steering-wheel/03.jpg"), alt: "Pagani Huayra steering wheel — tan leather close-up, front and detail views" } },
      { _type: "image-full", _key: "pag-04", image: { src: assetUrl("/images/projects/pagani-steering-wheel/04.jpg"), alt: "Pagani Huayra steering wheel — dark olive variant, front view" } },
      { _type: "video", _key: "pagani-video", video: { src: assetUrl("/videos/pagani-steering-wheel.mp4") } },
      { _type: "image-full", _key: "pag-06", image: { src: assetUrl("/images/projects/pagani-steering-wheel/06.jpg"), alt: "Pagani Huayra steering wheel — dark version, front and profile views" } },
      { _type: "image-full", _key: "pag-07", image: { src: assetUrl("/images/projects/pagani-steering-wheel/07.jpg"), alt: "Pagani logo" } },
    ],
  },
  {
    slug: "bow-timepiece",
    thumbnail: { src: assetUrl("/images/work/08.jpg"), alt: "BOW Nautical Timepiece Concept" },
    hasVideo: false,
    blocks: [
      { _type: "image-full", _key: "bow-01", image: { src: assetUrl("/images/projects/bow-timepiece/01.jpg"), alt: "BOW Timeless Value — yacht deck with logo" } },
      { _type: "image-full", _key: "bow-02", image: { src: assetUrl("/images/projects/bow-timepiece/02.jpg"), alt: "BOW concept sketches — watch design explorations on dark background" } },
      { _type: "image-pair", _key: "bow-pair-1", left: { src: assetUrl("/images/projects/bow-timepiece/03.jpg"), alt: "BOW watch — dark 3D render, perspective view" }, right: { src: assetUrl("/images/projects/bow-timepiece/04.jpg"), alt: "BOW watch — dark 3D render, rear view" } },
      { _type: "image-full", _key: "bow-05", image: { src: assetUrl("/images/projects/bow-timepiece/05.jpg"), alt: "BOW watch — twin propeller controls close-up" } },
      { _type: "image-full", _key: "bow-06", image: { src: assetUrl("/images/projects/bow-timepiece/06.jpg"), alt: "BOW watch — propeller detail with rotation mechanism" } },
      { _type: "image-full", _key: "bow-07", image: { src: assetUrl("/images/projects/bow-timepiece/07.jpg"), alt: "BOW watch — silver variant, full perspective render" } },
      { _type: "image-full", _key: "bow-08", image: { src: assetUrl("/images/projects/bow-timepiece/08.jpg"), alt: "BOW watch — silver variant with strap, side view" } },
      { _type: "image-full", _key: "bow-09", image: { src: assetUrl("/images/projects/bow-timepiece/09.jpg"), alt: "BOW watch — silver variant, three-quarter view" } },
      { _type: "image-full", _key: "bow-10", image: { src: assetUrl("/images/projects/bow-timepiece/10.jpg"), alt: "BOW watch — strap integration mechanism, four views" } },
      { _type: "image-full", _key: "bow-11", image: { src: assetUrl("/images/projects/bow-timepiece/11.jpg"), alt: "BOW Timeless Value — propellers emerging from water" } },
    ],
  },
  {
    slug: "modular-signage",
    thumbnail: { src: assetUrl("/images/work/10.jpg"), alt: "Modular Urban Signage System" },
    hasVideo: true,
    blocks: [
      { _type: "image-full", _key: "sig-01", image: { src: assetUrl("/images/projects/modular-signage/01.jpg"), alt: "Aluminium extrusion profile — one profile, multiple urban functions" } },
      { _type: "image-full", _key: "sig-02", image: { src: assetUrl("/images/projects/modular-signage/02.jpg"), alt: "Modular system components on workbench — one extrusion, endless configurations" } },
      { _type: "image-loop", _key: "sig-loop", images: [
        { src: assetUrl("/images/projects/modular-signage/loop-01.jpg"), alt: "Traffic signal system — daytime, green arrow", width: 2401, height: 1431 },
        { src: assetUrl("/images/projects/modular-signage/loop-02.jpg"), alt: "Traffic signal system — daytime with solar panel", width: 2401, height: 1432 },
        { src: assetUrl("/images/projects/modular-signage/loop-03.jpg"), alt: "Traffic signal system — nighttime, green arrow", width: 2401, height: 1432 },
        { src: assetUrl("/images/projects/modular-signage/loop-04.jpg"), alt: "Traffic signal system — nighttime, red arrow", width: 2401, height: 1432 },
      ], interval: 1500 },
      { _type: "image-full", _key: "sig-03", image: { src: assetUrl("/images/projects/modular-signage/03.jpg"), alt: "Public transport information — bus stop display at night" } },
      { _type: "image-full", _key: "sig-04", image: { src: assetUrl("/images/projects/modular-signage/04.jpg"), alt: "Cycling signal unit — cyclist approaching urban signal" } },
      { _type: "image-full", _key: "sig-05", image: { src: assetUrl("/images/projects/modular-signage/05.jpg"), alt: "Interactive tourist information — touchscreen terminal in public space" } },
      { _type: "image-full", _key: "sig-06", image: { src: assetUrl("/images/projects/modular-signage/06.jpg"), alt: "Public lighting unit — sunflower-type solar panel system at night" } },
      { _type: "video", _key: "sig-video", video: { src: assetUrl("/videos/modular-signage.mp4") } },
      { _type: "image-pair", _key: "sig-pair", left: { src: assetUrl("/images/projects/modular-signage/07.jpg"), alt: "Integrated camera — compact rotating module for discreet urban monitoring" }, right: { src: assetUrl("/images/projects/modular-signage/08.jpg"), alt: "Solar tracking — rotating panel system designed to follow the sun" } },
    ],
  },
  {
    slug: "shiftcore-footwear",
    thumbnail: { src: assetUrl("/images/work/09.jpg"), alt: "ShiftCore Modular Footwear Concept" },
    hasVideo: true,
    blocks: [
      { _type: "video", _key: "sc-video", video: { src: assetUrl("/videos/shiftcore-footwear.mp4") } },
      { _type: "image-full", _key: "sc-2", image: { src: assetUrl("/images/projects/shiftcore-footwear/image-2.jpg"), alt: "Swap the inner — adapt your footwear to your day" } },
      { _type: "image-full", _key: "sc-1", image: { src: assetUrl("/images/projects/shiftcore-footwear/image-1.jpg"), alt: "ShiftCore product views — shell, inner boot and assembled" } },
      { _type: "image-loop", _key: "sc-loop", images: [
        { src: assetUrl("/images/projects/shiftcore-footwear/loop-1.jpg"), alt: "ShiftCore colorway — orange", width: 2400, height: 1109 },
        { src: assetUrl("/images/projects/shiftcore-footwear/loop-2.jpg"), alt: "ShiftCore colorway — brown", width: 2400, height: 1109 },
        { src: assetUrl("/images/projects/shiftcore-footwear/loop-3.jpg"), alt: "ShiftCore colorway — olive", width: 2400, height: 1109 },
        { src: assetUrl("/images/projects/shiftcore-footwear/loop-4.jpg"), alt: "ShiftCore colorway — blue", width: 2400, height: 1109 },
        { src: assetUrl("/images/projects/shiftcore-footwear/loop-5.jpg"), alt: "ShiftCore colorway — yellow", width: 2400, height: 1109 },
        { src: assetUrl("/images/projects/shiftcore-footwear/loop-6.jpg"), alt: "ShiftCore colorway — grey", width: 2400, height: 1109 },
      ], interval: 600 },
      { _type: "image-full", _key: "sc-3", image: { src: assetUrl("/images/projects/shiftcore-footwear/image-3.jpg"), alt: "One shell. Multiple inners. Built to adapt." } },
      { _type: "image-full", _key: "sc-4", image: { src: assetUrl("/images/projects/shiftcore-footwear/image-4.jpg"), alt: "Leave the street at the door" } },
      { _type: "image-full", _key: "sc-5", image: { src: assetUrl("/images/projects/shiftcore-footwear/image-5.jpg"), alt: "Pack more. Carry less." } },
      { _type: "image-full", _key: "sc-6", image: { src: assetUrl("/images/projects/shiftcore-footwear/image-6.jpg"), alt: "Pack more. Carry less. — suitcase view" } },
      { _type: "image-full", _key: "sc-7", image: { src: assetUrl("/images/projects/shiftcore-footwear/image-7.jpg"), alt: "ShiftCore brand logo" } },
    ],
  },
  {
    slug: "bugatti-steering-wheel",
    thumbnail: { src: assetUrl("/images/work/06.jpg"), alt: "Bugatti Millenium Steering Wheel" },
    hasVideo: true,
    blocks: [
      { _type: "video", _key: "bugatti-video", video: { src: assetUrl("/videos/bugatti-steering-wheel.mp4") } },
      { _type: "image-full", _key: "bug-01", image: { src: assetUrl("/images/projects/bugatti-steering-wheel/01.jpg"), alt: "Bugatti Millenium steering wheel — white, front view on desk" } },
      { _type: "image-full", _key: "bug-02", image: { src: assetUrl("/images/projects/bugatti-steering-wheel/02.jpg"), alt: "Bugatti Millenium steering wheel — white, front and profile views" } },
      { _type: "image-full", _key: "bug-03", image: { src: assetUrl("/images/projects/bugatti-steering-wheel/03.jpg"), alt: "Bugatti Millenium steering wheel — white interior, two angles" } },
      { _type: "image-full", _key: "bug-04", image: { src: assetUrl("/images/projects/bugatti-steering-wheel/04.jpg"), alt: "Bugatti Millenium steering wheel — dark, front and profile views" } },
      { _type: "image-full", _key: "bug-05", image: { src: assetUrl("/images/projects/bugatti-steering-wheel/05.jpg"), alt: "Bugatti Millenium steering wheel — dark interior, Chiron cockpit" } },
      { _type: "image-full", _key: "bug-06", image: { src: assetUrl("/images/projects/bugatti-steering-wheel/06.jpg"), alt: "Bugatti Millenium steering wheel — brown, front and profile views" } },
      { _type: "image-full", _key: "bug-07", image: { src: assetUrl("/images/projects/bugatti-steering-wheel/07.jpg"), alt: "Bugatti Millenium steering wheel — brown interior, Chiron cockpit" } },
    ],
  },
];

export function getProject(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

export function getAdjacentProjects(slug: string) {
  const index = projects.findIndex((p) => p.slug === slug);
  if (index === -1) return { prev: undefined, next: undefined };

  const prev = projects[(index - 1 + projects.length) % projects.length];
  const next = projects[(index + 1) % projects.length];
  return { prev, next };
}
